# Generated by Django 5.0.6 on 2024-07-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_item_orderitem_items_remove_order_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='items',
            new_name='item',
        ),
    ]
